//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chimp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chimp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string _FontFamily {
            get {
                return ResourceManager.GetString("_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        public static string _FontSize {
            get {
                return ResourceManager.GetString("_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHIMP.
        /// </summary>
        public static string _Title {
            get {
                return ResourceManager.GetString("_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoboot Disabled.
        /// </summary>
        public static string Action_Bootable_Clear_Completed_Text {
            get {
                return ResourceManager.GetString("Action_Bootable_Clear_Completed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Autoboot.
        /// </summary>
        public static string Action_Bootable_Clear_Text {
            get {
                return ResourceManager.GetString("Action_Bootable_Clear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoboot Enabled.
        /// </summary>
        public static string Action_Bootable_Set_Completed_Text {
            get {
                return ResourceManager.GetString("Action_Bootable_Set_Completed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Autoboot.
        /// </summary>
        public static string Action_Bootable_Set_Text {
            get {
                return ResourceManager.GetString("Action_Bootable_Set_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Installation Successful.
        /// </summary>
        public static string Action_ClearOverlays_Completed_Text {
            get {
                return ResourceManager.GetString("Action_ClearOverlays_Completed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Canon Overlays.
        /// </summary>
        public static string Action_ClearOverlays_Text {
            get {
                return ResourceManager.GetString("Action_ClearOverlays_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eject Card.
        /// </summary>
        public static string Action_Eject_Text {
            get {
                return ResourceManager.GetString("Action_Eject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install {0}.
        /// </summary>
        public static string Action_Install_Format {
            get {
                return ResourceManager.GetString("Action_Install_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canon BASIC Disabled.
        /// </summary>
        public static string Action_Scriptable_Clear_Completed_Text {
            get {
                return ResourceManager.GetString("Action_Scriptable_Clear_Completed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Canon BASIC.
        /// </summary>
        public static string Action_Scriptable_Clear_Text {
            get {
                return ResourceManager.GetString("Action_Scriptable_Clear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canon BASIC Enabled.
        /// </summary>
        public static string Action_Scriptable_Set_Completed_Text {
            get {
                return ResourceManager.GetString("Action_Scriptable_Set_Completed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Canon BASIC.
        /// </summary>
        public static string Action_Scriptable_Set_Text {
            get {
                return ResourceManager.GetString("Action_Scriptable_Set_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Action.
        /// </summary>
        public static string Action_Select_Text {
            get {
                return ResourceManager.GetString("Action_Select_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to 2nd Partition.
        /// </summary>
        public static string Action_Switch_1_Text {
            get {
                return ResourceManager.GetString("Action_Switch_1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to 3rd Partition.
        /// </summary>
        public static string Action_Switch_2_Text {
            get {
                return ResourceManager.GetString("Action_Switch_2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to 4th Partition.
        /// </summary>
        public static string Action_Switch_3_Text {
            get {
                return ResourceManager.GetString("Action_Switch_3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partitions Switched.
        /// </summary>
        public static string Action_Switch_Completed_Text {
            get {
                return ResourceManager.GetString("Action_Switch_Completed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Partitions.
        /// </summary>
        public static string Action_Switch_Text {
            get {
                return ResourceManager.GetString("Action_Switch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Product.
        /// </summary>
        public static string Action_Unsupported_Text {
            get {
                return ResourceManager.GetString("Action_Unsupported_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0}.
        /// </summary>
        public static string Action_Update_Format {
            get {
                return ResourceManager.GetString("Action_Update_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string Camera_AllFiles_Text {
            get {
                return ResourceManager.GetString("Camera_AllFiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Camera_Browse_Content {
            get {
                return ResourceManager.GetString("Camera_Browse_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canon images.
        /// </summary>
        public static string Camera_CanonImages_Text {
            get {
                return ResourceManager.GetString("Camera_CanonImages_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible images.
        /// </summary>
        public static string Camera_CompatibleImages_Text {
            get {
                return ResourceManager.GetString("Camera_CompatibleImages_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Version:.
        /// </summary>
        public static string Camera_FirmwareVersion_Content {
            get {
                return ResourceManager.GetString("Camera_FirmwareVersion_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}{2} rev {3}.{4}{5}.
        /// </summary>
        public static string Camera_FirmwareVersion_Format {
            get {
                return ResourceManager.GetString("Camera_FirmwareVersion_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer:.
        /// </summary>
        public static string Camera_Make_Content {
            get {
                return ResourceManager.GetString("Camera_Make_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model:.
        /// </summary>
        public static string Camera_Model_Content {
            get {
                return ResourceManager.GetString("Camera_Model_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canon Metadata Not Found.
        /// </summary>
        public static string Camera_NoCanonMakernote_Text {
            get {
                return ResourceManager.GetString("Camera_NoCanonMakernote_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canon Firmware Revision Not Found.
        /// </summary>
        public static string Camera_NoFirmwareRevision_Text {
            get {
                return ResourceManager.GetString("Camera_NoFirmwareRevision_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Valid Images.
        /// </summary>
        public static string Camera_NoImage_Text {
            get {
                return ResourceManager.GetString("Camera_NoImage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Not Found.
        /// </summary>
        public static string Camera_NoMetadata_Text {
            get {
                return ResourceManager.GetString("Camera_NoMetadata_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canon Model ID Not Found.
        /// </summary>
        public static string Camera_NoModelId_Text {
            get {
                return ResourceManager.GetString("Camera_NoModelId_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Manufacturer.
        /// </summary>
        public static string Camera_NonCanon_Text {
            get {
                return ResourceManager.GetString("Camera_NonCanon_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        public static string Camera_SelectImage_Text {
            get {
                return ResourceManager.GetString("Camera_SelectImage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Detected.
        /// </summary>
        public static string Camera_Title_Detected_Text {
            get {
                return ResourceManager.GetString("Camera_Title_Detected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting Camera.
        /// </summary>
        public static string Camera_Title_Detecting_Text {
            get {
                return ResourceManager.GetString("Camera_Title_Detecting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Camera Model.
        /// </summary>
        public static string Camera_Title_Select_Text {
            get {
                return ResourceManager.GetString("Camera_Title_Select_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Model.
        /// </summary>
        public static string Camera_UnsupportedModel_Text {
            get {
                return ResourceManager.GetString("Camera_UnsupportedModel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Detected.
        /// </summary>
        public static string Card_Detected_Title_Text {
            get {
                return ResourceManager.GetString("Card_Detected_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting Card.
        /// </summary>
        public static string Card_Detecting_Title_Text {
            get {
                return ResourceManager.GetString("Card_Detecting_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive:.
        /// </summary>
        public static string Card_Drive_Content {
            get {
                return ResourceManager.GetString("Card_Drive_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string Card_Drive_Format {
            get {
                return ResourceManager.GetString("Card_Drive_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System:.
        /// </summary>
        public static string Card_FileSystem_Content {
            get {
                return ResourceManager.GetString("Card_FileSystem_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string Card_FileSystem_None {
            get {
                return ResourceManager.GetString("Card_FileSystem_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page will refresh automatically after the card is inserted..
        /// </summary>
        public static string Card_NoCard_Text {
            get {
                return ResourceManager.GetString("Card_NoCard_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Card.
        /// </summary>
        public static string Card_NoCard_Title_Text {
            get {
                return ResourceManager.GetString("Card_NoCard_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Card Drive.
        /// </summary>
        public static string Card_Select_Title_Text {
            get {
                return ResourceManager.GetString("Card_Select_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space:.
        /// </summary>
        public static string Card_Space_Content {
            get {
                return ResourceManager.GetString("Card_Space_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} B.
        /// </summary>
        public static string DiskSpace_Bytes_Format {
            get {
                return ResourceManager.GetString("DiskSpace_Bytes_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} free of {1}.
        /// </summary>
        public static string DiskSpace_Format {
            get {
                return ResourceManager.GetString("DiskSpace_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:.##} GB.
        /// </summary>
        public static string DiskSpace_GBytes_Format {
            get {
                return ResourceManager.GetString("DiskSpace_GBytes_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:.##} KB.
        /// </summary>
        public static string DiskSpace_KBytes_Format {
            get {
                return ResourceManager.GetString("DiskSpace_KBytes_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:.##} MB.
        /// </summary>
        public static string DiskSpace_MBytes_Format {
            get {
                return ResourceManager.GetString("DiskSpace_MBytes_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHDK_DE Stable.
        /// </summary>
        public static string Distro_CHDK_DE_release {
            get {
                return ResourceManager.GetString("Distro_CHDK_DE_release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHDK_DE Development.
        /// </summary>
        public static string Distro_CHDK_DE_trunk {
            get {
                return ResourceManager.GetString("Distro_CHDK_DE_trunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHDK Stable.
        /// </summary>
        public static string Distro_CHDK_release {
            get {
                return ResourceManager.GetString("Distro_CHDK_release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHDK Development.
        /// </summary>
        public static string Distro_CHDK_trunk {
            get {
                return ResourceManager.GetString("Distro_CHDK_trunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Lantern.
        /// </summary>
        public static string Distro_ML {
            get {
                return ResourceManager.GetString("Distro_ML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDM.
        /// </summary>
        public static string Distro_SDM {
            get {
                return ResourceManager.GetString("Distro_SDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Install.
        /// </summary>
        public static string Download_Completed_Text {
            get {
                return ResourceManager.GetString("Download_Completed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Download_Downloading_Text {
            get {
                return ResourceManager.GetString("Download_Downloading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting.
        /// </summary>
        public static string Download_Extracting_Text {
            get {
                return ResourceManager.GetString("Download_Extracting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Download Data.
        /// </summary>
        public static string Download_FetchingData_Text {
            get {
                return ResourceManager.GetString("Download_FetchingData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data Format.
        /// </summary>
        public static string Download_InvalidFormat_Text {
            get {
                return ResourceManager.GetString("Download_InvalidFormat_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded {0} of {1}.
        /// </summary>
        public static string Download_Progress_Format {
            get {
                return ResourceManager.GetString("Download_Progress_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Firmware Version.
        /// </summary>
        public static string Download_UnsupportedFirmware_Text {
            get {
                return ResourceManager.GetString("Download_UnsupportedFirmware_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Model.
        /// </summary>
        public static string Download_UnsupportedModel_Text {
            get {
                return ResourceManager.GetString("Download_UnsupportedModel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Metadata.
        /// </summary>
        public static string Download_Updating_Text {
            get {
                return ResourceManager.GetString("Download_Updating_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Up to Date.
        /// </summary>
        public static string Download_UpToDate_Text {
            get {
                return ResourceManager.GetString("Download_UpToDate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eject {0}.
        /// </summary>
        public static string Eject_CheckBox_Format {
            get {
                return ResourceManager.GetString("Eject_CheckBox_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecting Card.
        /// </summary>
        public static string Eject_Ejecting_Text {
            get {
                return ResourceManager.GetString("Eject_Ejecting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device &apos;{0}&apos; can now be safely removed from the computer..
        /// </summary>
        public static string Eject_ToastBody_Format {
            get {
                return ResourceManager.GetString("Eject_ToastBody_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe to Remove Hardware.
        /// </summary>
        public static string Eject_ToastTitle {
            get {
                return ResourceManager.GetString("Eject_ToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Aborted.
        /// </summary>
        public static string Install_Aborted_Text {
            get {
                return ResourceManager.GetString("Install_Aborted_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Successful.
        /// </summary>
        public static string Install_Completed_Text {
            get {
                return ResourceManager.GetString("Install_Completed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying Files.
        /// </summary>
        public static string Install_Copying_Text {
            get {
                return ResourceManager.GetString("Install_Copying_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Card Details.
        /// </summary>
        public static string Install_Format_Text {
            get {
                return ResourceManager.GetString("Install_Format_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting.
        /// </summary>
        public static string Install_Formatting_Text {
            get {
                return ResourceManager.GetString("Install_Formatting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        public static string Install_Initializing_Text {
            get {
                return ResourceManager.GetString("Install_Initializing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Partitions.
        /// </summary>
        public static string Install_Partitioning_Text {
            get {
                return ResourceManager.GetString("Install_Partitioning_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching Partitions.
        /// </summary>
        public static string Install_Switching_Text {
            get {
                return ResourceManager.GetString("Install_Switching_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Size Not Supported by Camera.
        /// </summary>
        public static string Install_UnsupportedCardSize_Text {
            get {
                return ResourceManager.GetString("Install_UnsupportedCardSize_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This utility installs Canon hacks onto memory cards and manages existing installations..
        /// </summary>
        public static string Intro_Message_Text {
            get {
                return ResourceManager.GetString("Intro_Message_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;header&quot;: &quot;SD cards only&quot;,
        ///    &quot;contents&quot;: [ &quot;MMC cards are unsupported (a microSD with an adapter is OK).&quot; ]
        ///  },
        ///  {
        ///    &quot;header&quot;: &quot;Ready to lock&quot;,
        ///    &quot;contents&quot;: [ &quot;The card must have a lock switch (barring a microSD camera).&quot; ]
        ///  },
        ///  {
        ///    &quot;header&quot;: &quot;Take a picture&quot;,
        ///    &quot;contents&quot;: [ &quot;At least one picture taken with the camera must be present.&quot; ]
        ///  },
        ///  {
        ///    &quot;header&quot;: &quot;Use a card reader&quot;,
        ///    &quot;contents&quot;: [ &quot;Connecting the camera with a cable is unsupported.&quot; ]
        ///  },
        ///  {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string intro_tips {
            get {
                return ResourceManager.GetString("intro_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        public static string Intro_Welcome_Format {
            get {
                return ResourceManager.GetString("Intro_Welcome_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Key_Menu {
            get {
                return ResourceManager.GetString("Key_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        public static string Key_Playback {
            get {
                return ResourceManager.GetString("Key_Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Key_Print {
            get {
                return ResourceManager.GetString("Key_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        public static string Key_Shrtcut {
            get {
                return ResourceManager.GetString("Key_Shrtcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Licenses_Accept_Content {
            get {
                return ResourceManager.GetString("Licenses_Accept_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept All.
        /// </summary>
        public static string Licenses_AcceptAll_Content {
            get {
                return ResourceManager.GetString("Licenses_AcceptAll_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Licenses_Reject_Text {
            get {
                return ResourceManager.GetString("Licenses_Reject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject All.
        /// </summary>
        public static string Licenses_RejectAll_Text {
            get {
                return ResourceManager.GetString("Licenses_RejectAll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Licenses.
        /// </summary>
        public static string Licenses_Title_Text {
            get {
                return ResourceManager.GetString("Licenses_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to abort the installation?.
        /// </summary>
        public static string MessageBox_Abort_Text {
            get {
                return ResourceManager.GetString("MessageBox_Abort_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBox_Error_Caption {
            get {
                return ResourceManager.GetString("MessageBox_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: This will erase ALL data on this disk.
        ///To continue, click OK. To quit, click CANCEL..
        /// </summary>
        public static string MessageBox_Format_Message {
            get {
                return ResourceManager.GetString("MessageBox_Format_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400plus.
        /// </summary>
        public static string Product_400plus {
            get {
                return ResourceManager.GetString("Product_400plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHDK.
        /// </summary>
        public static string Product_CHDK {
            get {
                return ResourceManager.GetString("Product_CHDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Lantern.
        /// </summary>
        public static string Product_ML {
            get {
                return ResourceManager.GetString("Product_ML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDM.
        /// </summary>
        public static string Product_SDM {
            get {
                return ResourceManager.GetString("Product_SDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1:D4}{2:D2}{3:D2}-{5:D2}.
        /// </summary>
        public static string Product_Version_400plus_Format {
            get {
                return ResourceManager.GetString("Product_Version_400plus_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1:D4}{2:D2}{3:D2}-{4}.
        /// </summary>
        public static string Product_Version_400plus_Format_3 {
            get {
                return ResourceManager.GetString("Product_Version_400plus_Format_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1:yyyyMMMdd}.
        /// </summary>
        public static string Product_Version_ML_Date_Format {
            get {
                return ResourceManager.GetString("Product_Version_ML_Date_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changeset:.
        /// </summary>
        public static string Software_Changeset_Content {
            get {
                return ResourceManager.GetString("Software_Changeset_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by:.
        /// </summary>
        public static string Software_Creator_Content {
            get {
                return ResourceManager.GetString("Software_Creator_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string Software_Date_Content {
            get {
                return ResourceManager.GetString("Software_Date_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd MMM yyyy}.
        /// </summary>
        public static string Software_Date_Format {
            get {
                return ResourceManager.GetString("Software_Date_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Software_Date_Unknown_Text {
            get {
                return ResourceManager.GetString("Software_Date_Unknown_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Software_Language_Content {
            get {
                return ResourceManager.GetString("Software_Language_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Software_Language_Unknown_Text {
            get {
                return ResourceManager.GetString("Software_Language_Unknown_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules:.
        /// </summary>
        public static string Software_Modules_Content {
            get {
                return ResourceManager.GetString("Software_Modules_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform:.
        /// </summary>
        public static string Software_Platform_Content {
            get {
                return ResourceManager.GetString("Software_Platform_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Software_Platform_Unknown_Text {
            get {
                return ResourceManager.GetString("Software_Platform_Unknown_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product:.
        /// </summary>
        public static string Software_Product_Content {
            get {
                return ResourceManager.GetString("Software_Product_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Software_Product_Unknown_Text {
            get {
                return ResourceManager.GetString("Software_Product_Unknown_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision:.
        /// </summary>
        public static string Software_Revision_Content {
            get {
                return ResourceManager.GetString("Software_Revision_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Software_Revision_Unknown_Text {
            get {
                return ResourceManager.GetString("Software_Revision_Unknown_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        public static string Software_Status_alpha {
            get {
                return ResourceManager.GetString("Software_Status_alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        public static string Software_Status_beta {
            get {
                return ResourceManager.GetString("Software_Status_beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string Software_Status_Content {
            get {
                return ResourceManager.GetString("Software_Status_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        public static string Software_Status_final {
            get {
                return ResourceManager.GetString("Software_Status_final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-alpha.
        /// </summary>
        public static string Software_Status_prealpha {
            get {
                return ResourceManager.GetString("Software_Status_prealpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Software_Status_Unknown {
            get {
                return ResourceManager.GetString("Software_Status_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string Software_Time_Content {
            get {
                return ResourceManager.GetString("Software_Time_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:T}.
        /// </summary>
        public static string Software_Time_Format {
            get {
                return ResourceManager.GetString("Software_Time_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Software_Time_Unknown_Text {
            get {
                return ResourceManager.GetString("Software_Time_Unknown_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Software Detected.
        /// </summary>
        public static string Software_Title_Detected_Text {
            get {
                return ResourceManager.GetString("Software_Title_Detected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting Camera Software.
        /// </summary>
        public static string Software_Title_Detecting_Text {
            get {
                return ResourceManager.GetString("Software_Title_Detecting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Camera Software Detected.
        /// </summary>
        public static string Software_Title_None_Text {
            get {
                return ResourceManager.GetString("Software_Title_None_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Camera Software.
        /// </summary>
        public static string Software_Title_Select_Text {
            get {
                return ResourceManager.GetString("Software_Title_Select_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Product Detected.
        /// </summary>
        public static string Software_Title_Unknown_Text {
            get {
                return ResourceManager.GetString("Software_Title_Unknown_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Product Detected.
        /// </summary>
        public static string Software_Title_Unsupported_Text {
            get {
                return ResourceManager.GetString("Software_Title_Unsupported_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Software_Version_Content {
            get {
                return ResourceManager.GetString("Software_Version_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Software_Version_Unknown_Text {
            get {
                return ResourceManager.GetString("Software_Version_Unknown_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Step_Action_Text {
            get {
                return ResourceManager.GetString("Step_Action_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Camera.
        /// </summary>
        public static string Step_Camera_Text {
            get {
                return ResourceManager.GetString("Step_Camera_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Card.
        /// </summary>
        public static string Step_Card_Text {
            get {
                return ResourceManager.GetString("Step_Card_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Step_Download_Text {
            get {
                return ResourceManager.GetString("Step_Download_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eject Card.
        /// </summary>
        public static string Step_Eject_Text {
            get {
                return ResourceManager.GetString("Step_Eject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Step_Install_Text {
            get {
                return ResourceManager.GetString("Step_Install_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Step_Intro_Text {
            get {
                return ResourceManager.GetString("Step_Intro_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Step_Licenses_Text {
            get {
                return ResourceManager.GetString("Step_Licenses_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Software.
        /// </summary>
        public static string Step_Software_Text {
            get {
                return ResourceManager.GetString("Step_Software_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Step_Summary_Text {
            get {
                return ResourceManager.GetString("Step_Summary_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Aborted.
        /// </summary>
        public static string Summary_Aborted_Title_Text {
            get {
                return ResourceManager.GetString("Summary_Aborted_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the {0} button to enter the {1} ALT mode..
        /// </summary>
        public static string Summary_AltMode_Format {
            get {
                return ResourceManager.GetString("Summary_AltMode_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALT mode.
        /// </summary>
        public static string Summary_AltMode_Header {
            get {
                return ResourceManager.GetString("Summary_AltMode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to access the camera&apos;s built-in menu, hold the Menu button for 1 sec..
        /// </summary>
        public static string Summary_AltMode_Menu_Text {
            get {
                return ResourceManager.GetString("Summary_AltMode_Menu_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to switch to Playback mode, hold the Playback button for 1 sec..
        /// </summary>
        public static string Summary_AltMode_Playback_Text {
            get {
                return ResourceManager.GetString("Summary_AltMode_Playback_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to print a photo, hold the Print button for 1 sec..
        /// </summary>
        public static string Summary_AltMode_Print_Text {
            get {
                return ResourceManager.GetString("Summary_AltMode_Print_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show camera-specific notes.
        /// </summary>
        public static string Summary_CameraNotes_Content {
            get {
                return ResourceManager.GetString("Summary_CameraNotes_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camnotes.txt.
        /// </summary>
        public static string Summary_CHDK_CameraNotes_FileName {
            get {
                return ResourceManager.GetString("Summary_CHDK_CameraNotes_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has been successfully installed onto {3}..
        /// </summary>
        public static string Summary_Completed_Format {
            get {
                return ResourceManager.GetString("Summary_Completed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Complete.
        /// </summary>
        public static string Summary_Completed_Title_Text {
            get {
                return ResourceManager.GetString("Summary_Completed_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove safely.
        /// </summary>
        public static string Summary_Eject_Header {
            get {
                return ResourceManager.GetString("Summary_Eject_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Safely Remove Hardware and Eject Media option before removing the card..
        /// </summary>
        public static string Summary_Eject_Text {
            get {
                return ResourceManager.GetString("Summary_Eject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for LED.
        /// </summary>
        public static string Summary_EOS_Led_Header {
            get {
                return ResourceManager.GetString("Summary_EOS_Led_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for LED confirmation (or for 5 seconds) before removing the card from camera..
        /// </summary>
        public static string Summary_EOS_Led_Text {
            get {
                return ResourceManager.GetString("Summary_EOS_Led_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To uninstall from the card, format it in the camera..
        /// </summary>
        public static string Summary_EOS_Remove_2_Text {
            get {
                return ResourceManager.GetString("Summary_EOS_Remove_2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To uninstall from the camera, launch Firmware Update and follow the instructions..
        /// </summary>
        public static string Summary_EOS_Remove_3_Text {
            get {
                return ResourceManager.GetString("Summary_EOS_Remove_3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do NOT delete the {0} files from the card..
        /// </summary>
        public static string Summary_EOS_Remove_Format {
            get {
                return ResourceManager.GetString("Summary_EOS_Remove_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card must be locked in order for {0} to load..
        /// </summary>
        public static string Summary_LockCard_Format {
            get {
                return ResourceManager.GetString("Summary_LockCard_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock and load.
        /// </summary>
        public static string Summary_LockCard_Header {
            get {
                return ResourceManager.GetString("Summary_LockCard_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the Menu button in ALT mode to access the CHDK menu..
        /// </summary>
        public static string Summary_Menu_CHDK_Text {
            get {
                return ResourceManager.GetString("Summary_Menu_CHDK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the Delete button to access the {0} menu..
        /// </summary>
        public static string Summary_Menu_Format {
            get {
                return ResourceManager.GetString("Summary_Menu_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} menu.
        /// </summary>
        public static string Summary_Menu_Header_Format {
            get {
                return ResourceManager.GetString("Summary_Menu_Header_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold the Menu button for 1 sec in ALT mode to access the SDM menu..
        /// </summary>
        public static string Summary_Menu_SDM_Text {
            get {
                return ResourceManager.GetString("Summary_Menu_SDM_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card door must be open in order for {0} to load..
        /// </summary>
        public static string Summary_OpenCardDoor_Format {
            get {
                return ResourceManager.GetString("Summary_OpenCardDoor_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open card door.
        /// </summary>
        public static string Summary_OpenCardDoor_Header {
            get {
                return ResourceManager.GetString("Summary_OpenCardDoor_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling.
        /// </summary>
        public static string Summary_Remove_Header {
            get {
                return ResourceManager.GetString("Summary_Remove_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sdm.camera/sdm/documentation/SDM_User_Manual.pdf.
        /// </summary>
        public static string Summary_SDM_UserManual_Url {
            get {
                return ResourceManager.GetString("Summary_SDM_UserManual_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CHDK splash screen should appear shortly after the camera is powered up..
        /// </summary>
        public static string Summary_SplashScreen_CHDK_Text {
            get {
                return ResourceManager.GetString("Summary_SplashScreen_CHDK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SDM welcome screen should appear shortly after starting in Playback mode..
        /// </summary>
        public static string Summary_SplashScreen_SDM_Text {
            get {
                return ResourceManager.GetString("Summary_SplashScreen_SDM_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the Shutter Release button in ALT mode to switch to English..
        /// </summary>
        public static string Summary_SwitchLanguage_2_Text {
            get {
                return ResourceManager.GetString("Summary_SwitchLanguage_2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is installed with {1} as the menu language..
        /// </summary>
        public static string Summary_SwitchLanguage_Format {
            get {
                return ResourceManager.GetString("Summary_SwitchLanguage_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to English.
        /// </summary>
        public static string Summary_SwitchLanguage_Header {
            get {
                return ResourceManager.GetString("Summary_SwitchLanguage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the User Manual.
        /// </summary>
        public static string Summary_UserManual_Content {
            get {
                return ResourceManager.GetString("Summary_UserManual_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Wizard_Close {
            get {
                return ResourceManager.GetString("Wizard_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Wizard_Continue {
            get {
                return ResourceManager.GetString("Wizard_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Wizard_Finish {
            get {
                return ResourceManager.GetString("Wizard_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string Wizard_GoBack {
            get {
                return ResourceManager.GetString("Wizard_GoBack", resourceCulture);
            }
        }
    }
}
